# Generated by Django 3.0.5 on 2021-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_id', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('supply', models.CharField(max_length=50)),
                ('maxSupply', models.CharField(max_length=50)),
                ('marketCapUsd', models.CharField(max_length=50)),
                ('volumeUsd24Hr', models.CharField(max_length=50)),
                ('priceUsd', models.CharField(max_length=50)),
                ('changePercent24Hr', models.CharField(max_length=50)),
                ('vwap24Hr', models.CharField(max_length=50)),
                ('explorer', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
